name: Deploy AWS CDK

on:
  #   push:
  #     branches: [ main ]
  #   pull_request:
  #     branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  aws_cdk_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_DEV_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_DEV_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.1.1
        with:
          node-version: 14

      - name: Install AWS CDK
        run: 'npm install -g aws-cdk'

      - name: Install Infrastructure Depedency
        run: yarn install
        working-directory: infrastructure

      - name: CDK Deploy
        run: |
          cdk bootstrap --context @aws-cdk/core:newStyleStackSynthesis=1 --cloudformation-execution-policies arn:aws:iam::aws:policy/AdministratorAccess aws://849944574596/ap-southeast-2
          cdk deploy
        working-directory: infrastructure
